# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

def count_set_bits(number):
  count=0
  while(number>0):
    unit=number%2
    if(unit==1):
      count=count+1
    number=number//2
  return count

if __name__=="__main__":
  num=int(input())
  c=count_set_bits(num)
  print(c)

