# -*- coding: utf-8 -*-
"""next_permutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *

def next_permutation(permutation,n):

  index=-1
  for i in range(n-2,-1,-1):
    if(permutation[i+1]>permutation[i]):
      index=i
      break

  if(index==-1):
    return permutation[::-1]

  large=999999999
  for i in range(n-1,index,-1):
    if(permutation[i]>permutation[index] and permutation[i]<large):
      temp=i
      large=permutation

  permutation[index],permutation[temp]=permutation[temp],permutation[index]
  temp1=permutation[0:index+1]
  temp2=permutation[index+1:]
  temp2=temp2[::-1]
  temp1=temp1+temp2
  return temp1



def main():
  n=int(input('Enter the value of n'))
  print('Enter the array of elements')
  arr = list(map(int, input().split()))
  x=next_permutation(arr,n)
  print(f'The lexicographically next permutation is {arr}')


if __name__=="__main__":
  main()

