# -*- coding: utf-8 -*-
"""rod_cutting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *

def rod_cutting(n):
  rods=([0 for i in range(n+1)])

  for i in range(2,n+1):
    for j in range(1,(i//2)+1):
      rods[i]=max(rods[i],j*(i-j),j*rods[i-j])

  return rods[n]


def main():
  n=int(input('Enter the value of n'))
  maximum=rod_cutting(n)
  print(f'The maximum product possible by cutting the rod is {maximum}.')


if __name__=="__main__":
  main()

