# -*- coding: utf-8 -*-
"""coins_possible_combinations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *

def coin_combinations(denominations,value):
  arr=([0 for i in range(value+1)])
  arr[0]=1
  for i in range(1,value+1):
    for j in range(len(denominations)):
      if(i-denominations[j]>=0):
        arr[i]=arr[i]+arr[i-denominations[j]]

  return arr[value]


def main():
  print('Enter the denominations array')
  denominations = list(map(int, input().split()))
  sum_value=int(input('Enter the sum value'))
  number_ways=coin_combinations(denominations,sum_value)
  print(f'The number of possible combinations of sum {sum_value} from the given denominations is {number_ways}.')


if __name__=="__main__":
  main()

