# -*- coding: utf-8 -*-
"""minimizing coins.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *
import sys

def minimizing_coins(denominations,value):
  dp=([sys.maxsize for i in range(value+1)])

  dp[0]=0
  for i in range(value+1):
    for j in range(len(denominations)):
      if(i-denominations[j]>=0):
        dp[i]=min(dp[i],dp[i-denominations[j]]+1)

  return dp[value]
  

def main():
  print('Enter the denominations array')
  denominations = list(map(int, input().split()))
  sum_value=int(input('Enter the sum value'))
  number_ways=minimizing_coins(denominations,sum_value)
  print(f'The minimum number of coins required to obtain a sum of {sum_value} from the given denominations is {number_ways}.')


if __name__=="__main__":
  main()

