# -*- coding: utf-8 -*-
"""Trapping_rain_water.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *
import sys

#Trapping rain water in between the blocks
def trapping_rain_water(arr,n):
  left=[0] * n
  right=[0] * n

  water=0

  left[0]=arr[0]
  for i in range(1,n):
    left[i]=max(left[i-1],arr[i])

  right[n-1]=arr[n-1]
  for i in range(n-2,-1,-1):
    right[i]=max(right[i+1],arr[i])

  for i in range(0,n):
    minimum=min(left[i],right[i])
    x=minimum-arr[i]
    water=water+x

  return water


def main():
  n=int(input('Enter the value of n'))
  print('Enter the array of elements')
  arr = list(map(int, input().split()))
  x=trapping_rain_water(arr,n)
  print(f'The maximum amount of rain water than can be trapped between these blocks is {x}.')


if __name__=="__main__":
  main()

