# -*- coding: utf-8 -*-
"""Minimum_number_platforms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xX9h5ywVbAQHVxHbK_9lqAtnvWYpNhSK
"""

"""
 Minimum number of platforms required:-

 We are given two arrays that represent the arrival and 
 departure times of trains that stop at the platform. 
 We need to find the minimum number of platforms needed 
 at the railway station so that no train has to wait.

 Input- 
  N=6 
  arr[] = {9:00, 9:45, 9:55, 11:00, 15:00, 18:00} 
  dep[] = {9:20, 12:00, 11:30, 11:50, 19:00, 20:00}

 Output- 3

"""

from typing import List

def count_platforms(arr,dep,n):
  arr.sort()
  dep.sort()

  i=1
  j=0
  plat=1
  result=1
  while i<n and j<n:

    if(arr[i]<=dep[j]):
      plat=plat+1
      i=i+1

    else:
      plat=plat-1
      j=j+1
    result= max(result,plat)
  return result


def main():
  print('Enter the arrival time of trains')
  arr = list(map(int, input().split()))
  print('Enter the departure time of trains')
  dep = list(map(int, input().split()))
  n=len(arr)
  x=count_platforms(arr,dep,n)
  print(f'The minimum number of platforms required are {x}.')


if __name__=="__main__":
  main()

