# -*- coding: utf-8 -*-
"""jump_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xX9h5ywVbAQHVxHbK_9lqAtnvWYpNhSK
"""

"""
  Jump game-

  Given an array where each index marks the number of jumps that
  can be taken from that index, then find if the end of the
  array can be reached or not.

  Input- {1, 2, 0, 3, 0, 0} 
  Output- Yes, the end of array can be reached.

  Input- {1, 0, 2}
  Output - No, the end of array cannot be reached.

"""

from typing import List

def jump_game(arr,n):

  maximum_reach=0
  i=0
  while i<n and i<=maximum_reach:
    maximum_reach=max(arr[i]+i,maximum_reach)
    i=i+1

  if(i==n):
    return 1
  else:
    return 0


def main():
  print('Enter the array elements')
  arr = list(map(int, input().split()))
  n=len(arr)
  x=jump_game(arr,n)
  if(x==1):
    print('Yes, we can reach the end of the array.')
  else:
    print('No, we cannot reach the end of the array.')
  

if __name__=="__main__":
  main()

