# -*- coding: utf-8 -*-
"""valid_parentheses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xX9h5ywVbAQHVxHbK_9lqAtnvWYpNhSK
"""

"""
  Valid Parentheses:

  Given a string consisting only of '{' '}'
  '(' ')' '[' ']' , determine whether the parantheses
  are balanced or not.

  Input: [()]{}{[()()]()}
  Output: Balanced

  Input: [(])
  Output: Not Balanced

"""

from typing import List

def isValidParenthesis(expression):

    stack=[]
    opening=set('({[')
    closing=set('}])')
    pair = {')' : '(' , ']' : '[' , '}' : '{'}
    for i in range(len(expression)):
        if(expression[i] in opening):
            stack.append(expression[i])
        if(expression[i] in closing):
            if not stack:
                return 0
            elif stack.pop()!=pair[expression[i]]:
                return 0
            else:
                continue
    if not stack:
        return True
    else:
        return False

def main():
   str = input().strip()
   ans = isValidParenthesis(str)

   if ans:
      print("Balanced")
        
   else:
      print("Not Balanced")

  

if __name__=="__main__":
  main()

