# -*- coding: utf-8 -*-
"""form_smallest_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_QyT8VlAu2EmXdD-cmrgPjjIkgLUgvU
"""

"""
  You are given a string s, a string chars of distinct characters and an integer array vals of the same length as chars.
  The cost of the substring is the sum of the values of each character in the substring. The cost of an empty string is considered 0.

  The value of the character is defined in the following way:
  1. If the character is not in the string chars, then its value is its corresponding position (1-indexed) in the alphabet.
  For example, the value of 'a' is 1, the value of 'b' is 2, and so on. The value of 'z' is 26.

  Otherwise, assuming i is the index where the character occurs in the string chars, then its value is vals[i].
  Return the maximum cost among all substrings of the string s.

  Input: s = "adaa", chars = "d", vals = [-1000]
  Output: 2

  Input: s = "abc", chars = "abc", vals = [-1,-1,-1]
  Output: 0
  
"""


from typing import List

class Solution:
    def maximumCostSubstring(self, s: str, chars: str, vals: List[int]) -> int:
        sum1=0
        tsum=0
        for i in range(len(s)):
            if(s[i] in chars):
                index=chars.index(s[i])
                sum1=sum1+vals[index]
                if(sum1<0):
                    sum1=0
                if(sum1>tsum):
                    tsum=sum1
            else:
                sum1=sum1+ord(s[i])-96
                if(sum1<0):
                    sum1=0
                if(sum1>tsum):
                    tsum=sum1
        return tsum
        print(tsum)
        
strs=input()
x=input()
arr1 = list(map(int, input().split()))
ob=Solution()
sum1=ob.maximumCostSubstring(strs,x,arr1)
print(sum1)

