# -*- coding: utf-8 -*-
"""accept_the_challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_QyT8VlAu2EmXdD-cmrgPjjIkgLUgvU
"""

"""
  Choose any positive integer x and perform the following operation atleast twice.
  Add x to your current score and double the value of x.

  After performing the abive operation, the score should be exactly k.
  Print the largest x to start with or return -1 in case no such x exists.

  Input- 7       Output- 1
  Input- 8       Output- -1

"""


class Solution:
    def acceptTheChallenge(self, k):
        
        y=3
        x1=4
        ans=-1
        if(k%3==0):
            ans=k//3
        while True:
            if(y>=k):
                break
            y=y+x1
            x1=x1*2
            if(k%y==0):
                ans=max(ans,k//y)
        return ans

x=int(input())
ob=Solution()
ans=ob.acceptTheChallenge(x)
print(ans)

