# -*- coding: utf-8 -*-
"""exceptionally_odd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_QyT8VlAu2EmXdD-cmrgPjjIkgLUgvU
"""

"""
  Given an array of N positive integers where all numbers occur even number 
  of times except one number which occurs odd number of times. 
  Find the exceptional number.

  Input: N = 7
         Arr[] = {1, 2, 3, 2, 3, 1, 3}
  Output: 3

"""

class Solution:
    def getOddOccurrence(self, arr, n):
        # code here 
        diction={}
        for i in arr:
            if i in diction:
                diction[i]+=1
            else:
                diction[i]=1
        for key,value in diction.items():
            if value%2!=0:
                return key

arr = list(map(int, input().split()))
n=len(arr)
ob=Solution()
ans=ob.getOddOccurrence(arr,n)
print(ans)

