# -*- coding: utf-8 -*-
"""power_set_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_QyT8VlAu2EmXdD-cmrgPjjIkgLUgvU
"""

"""
  Given a string S, Find all the possible subsequences of the String in lexicographically-sorted order.

  Input : str = "abc"
  Output: a ab abc ac b bc c
  Explanation : There are 7 subsequences that 
                can be formed from abc.

"""


class Solution:
  def AllPossibleStrings(self, s):
    n = len(s)
    p = 2 ** n   # total number of power sets 
    res = []
    for i in range(1, p):
        tmp = ''
        for j in range(n):
            if i & (1 << j):
                tmp += s[j]
        res.append(tmp)

        #print(sorted(res)) 
    return sorted(res)

s=input()
ob=Solution()
ans=ob.AllPossibleStrings(s)
print(ans)

