# -*- coding: utf-8 -*-
"""josephus_problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_QyT8VlAu2EmXdD-cmrgPjjIkgLUgvU
"""

"""
  Josephus Problem:

  Using bit representation- 
  For example-

  Input - 9  : 1001
  Output- 3   : 0011

"""

def msbPos(n):
	pos = 0
	while n != 0:
		pos += 1
		n = n >> 1
	return pos

def josephify(n):
	
	position = msbPos(n)
	j = 1 << (position - 1)

	n = n ^ j
	n = n << 1
	n = n | 1

	return n


n = int(input()) 
print (josephify(n))

