# -*- coding: utf-8 -*-
"""sum_of_square_nums.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfwrahhEYGANgbDN7DO3D3a-alw6Bler
"""

# Time:  O(sqrt(c) * logc)
# Space: O(1)

# Given a non-negative integer c,task is to decide
# whether there're two integers a and b such that a2 + b2 = c.
#
# Example 1:
# Input: 5
# Output: True
# Explanation: 1 * 1 + 2 * 2 = 5


import math


class Solution(object):
    def judgeSquareSum(self, c):

        for a in range(int(math.sqrt(c))+1):
            b = int(math.sqrt(c-a**2))
            if a**2 + b**2 == c:
                return True
        return False

print(Solution().judgeSquareSum(5))

