# -*- coding: utf-8 -*-
"""water_and_jug.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfwrahhEYGANgbDN7DO3D3a-alw6Bler
"""

# Time:  O(logn),  n is the max of (x, y)
# Space: O(1)

# You are given two jugs with capacities x and y litres.
# There is an infinite amount of water supply available.
# You need to determine whether it is possible to
# measure exactly z litres using these two jugs.
#
# Operations allowed:
#
# Fill any of the jugs completely.
# Empty any of the jugs.
# Pour water from one jug into another till
# the other jug is completely full or
# the first jug itself is empty.

class Solution(object):
    def canMeasureWater(self, x, y, z):
        
        def gcd(a, b):
            while b:
                a, b = b, a%b
            return a
        return z == 0 or ((z <= x + y) and (z % gcd(x, y) == 0))

print(Solution().canMeasureWater(2,6,4))
print(Solution().canMeasureWater(2,6,5))
# Input: x = 2, y = 6, z = 4
# Output: True
# Example 2:
#
# Input: x = 2, y = 6, z = 5
# Output: False

