# -*- coding: utf-8 -*-
"""efficient_linking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19t5ihEIJ1CzUTqgAyf7i9Q5pvJ0bxH_U
"""

"""
  There are 20 officers in Chefland who can link the PAN to Aadhar.
  N applications were received for linking PAN. However, due to an internal conflict, 
  each officer intends to process exactly the same number of applications.

  Determine the minimum number of applications that would remain unprocessed.

"""
t=int(input())
for i in range(t):
    n=int(input())
    if(n<20):
        print(n)
    elif(n==20):
        print(1)
    else:
        x=n//20
        print(n-20*x)

