# -*- coding: utf-8 -*-
"""largest_subarray_sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *
def subarray_sum(arr,n):
  curr_sum=0
  max_sum=0
  for i in range(n):
    curr_sum=curr_sum+arr[i]
    if(curr_sum<0):
      curr_sum=0
    if(curr_sum>max_sum):
      max_sum=curr_sum

  return max_sum

def main():
  n=int(input("Enter n"))
  print("Enter the array values")
  arr = list(map(int, input().split()))

  max_sum=subarray_sum(arr,n)
  print(f'The maximum subarray sum is {max_sum}')


if __name__=="__main__":
  main()

