# -*- coding: utf-8 -*-
"""longest_common_prefix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQBoE_H6m4qF3Sjc3xblntUAR58GeS8N
"""

from math import *

def longest_common_prefix(strs):
  strs.sort()
  temp=""

  length=len(strs)
  x=strs[0]
  y=strs[length-1]

  i=0
  while(i<len(x)):
    if(x[i]==y[i]):
      temp=temp+x[i]
    else:
      break
    i=i+1

  return temp


def main():
  print('Enter the list of strings')
  strs= list(map(str, input().split()))
  ret_string=longest_common_prefix(strs)
 
  print(f"The longest common prefix found is '{ret_string}'")


if __name__=="__main__":
  main()

